"""empty message

Revision ID: 43a8f2076029
Revises: 0106415701e8
Create Date: 2021-04-27 23:10:56.662144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a8f2076029'
down_revision = '0106415701e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mail', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mail')
    # ### end Alembic commands ###
