"""empty message

Revision ID: 853d38bf3a94
Revises: 76639d847451
Create Date: 2021-04-12 23:53:45.277004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853d38bf3a94'
down_revision = '76639d847451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
