"""empty message

Revision ID: a2e02b602388
Revises: 7f0e75277fcc
Create Date: 2021-04-12 22:13:48.681431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e02b602388'
down_revision = '7f0e75277fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quote', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quote', type_='foreignkey')
    op.drop_column('quote', 'user_id')
    # ### end Alembic commands ###
